/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Resume */
        post: operations["generate_resume_api_resume_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume/render-tex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Render Resume Tex */
        post: operations["render_resume_tex_api_resume_render_tex_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Resume */
        post: operations["analyze_resume_api_resume_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume/analyze-job-description": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Job Description */
        post: operations["analyze_job_description_api_resume_analyze_job_description_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume/rewrite-bullets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rewrite Resume Bullets */
        post: operations["rewrite_resume_bullets_api_resume_rewrite_bullets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Resume */
        post: operations["save_resume_api_resume_save_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume/{resume_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Resume */
        get: operations["get_resume_api_resume__resume_id__get"];
        /** Update Resume */
        put: operations["update_resume_api_resume__resume_id__put"];
        post?: never;
        /** Delete Resume */
        delete: operations["delete_resume_api_resume__resume_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Achievement */
        Achievement: {
            /**
             * Title
             * @default
             */
            title: string;
            /** Description */
            description?: string | null;
            /** Date */
            date?: string | null;
        };
        /** AnalyzeJobDescriptionRequest */
        AnalyzeJobDescriptionRequest: {
            resume: components["schemas"]["Resume"];
            /**
             * Target Role
             * @default
             */
            target_role: string;
            /**
             * Target Company
             * @default
             */
            target_company: string;
            /** Job Description */
            job_description: string;
        };
        /** AnalyzeJobDescriptionResponse */
        AnalyzeJobDescriptionResponse: {
            /** Jd Keywords */
            jd_keywords?: string[];
            /** Matched Keywords */
            matched_keywords?: string[];
            /** Missing Keywords */
            missing_keywords?: string[];
            /** Keyword Match Percentage */
            keyword_match_percentage: number;
            /** Role Alignment Score */
            role_alignment_score: number;
            /** Keyword Details */
            keyword_details?: components["schemas"]["JobDescriptionKeywordMatch"][];
            /** Safe Suggestions */
            safe_suggestions?: components["schemas"]["MissingKeywordSuggestion"][];
        };
        /** AnalyzeResumeRequest */
        AnalyzeResumeRequest: {
            resume: components["schemas"]["Resume"];
            /**
             * Target Role
             * @default
             */
            target_role: string;
            /**
             * Target Company
             * @default
             */
            target_company: string;
        };
        /** AnalyzeResumeResponse */
        AnalyzeResumeResponse: {
            /** Ats Score */
            ats_score: number;
            /** Recruiter Readability Score */
            recruiter_readability_score: number;
            /** Role Fit Score */
            role_fit_score: number;
            /** Company Fit Score */
            company_fit_score: number;
            /** Missing Keywords */
            missing_keywords?: string[];
            /** Matched Keywords */
            matched_keywords?: string[];
            /** Keyword Matches */
            keyword_matches?: components["schemas"]["KeywordMatch"][];
            /** Weak Bullets */
            weak_bullets?: components["schemas"]["BulletFinding"][];
            /** Missing Metrics */
            missing_metrics?: components["schemas"]["BulletFinding"][];
            /** Section Quality Issues */
            section_quality_issues?: components["schemas"]["SectionQualityIssue"][];
            /** Keyword Evidence */
            keyword_evidence?: components["schemas"]["KeywordEvidence"][];
            /** Missing Keyword Suggestions */
            missing_keyword_suggestions?: components["schemas"]["MissingKeywordSuggestion"][];
            /** Bullet Quality */
            bullet_quality?: components["schemas"]["BulletQuality"][];
            /** Improvement Checklist */
            improvement_checklist?: components["schemas"]["ImprovementChecklistItem"][];
            /** Section Score Breakdown */
            section_score_breakdown?: components["schemas"]["SectionScoreBreakdown"][];
        };
        /** BulletFinding */
        BulletFinding: {
            /** Section */
            section: string;
            /** Item Index */
            item_index: number;
            /** Bullet Index */
            bullet_index: number;
            /** Label */
            label: string;
            /** Original */
            original: string;
            /** Reasons */
            reasons?: string[];
        };
        /** BulletQuality */
        BulletQuality: {
            /** Section */
            section: string;
            /** Item Index */
            item_index: number;
            /** Bullet Index */
            bullet_index: number;
            /** Label */
            label: string;
            /** Original */
            original: string;
            /** Score */
            score: number;
            /** Weakness Types */
            weakness_types?: string[];
            /** Reason */
            reason: string;
        };
        /** BulletRewrite */
        BulletRewrite: {
            /** Section */
            section: string;
            /** Item Index */
            item_index: number;
            /** Bullet Index */
            bullet_index: number;
            /** Label */
            label: string;
            /** Original */
            original: string;
            /** Rewritten */
            rewritten: string;
            /** Weak Terms */
            weak_terms?: string[];
            /** Rewrite Source */
            rewrite_source: string;
            /** Changed */
            changed: boolean;
            /** Metric Suggestion */
            metric_suggestion?: string | null;
            /** Notes */
            notes?: string[];
        };
        /** Certification */
        Certification: {
            /**
             * Title
             * @default
             */
            title: string;
            /** Issuer */
            issuer?: string | null;
            /** Date */
            date?: string | null;
            /** Link */
            link?: string | null;
        };
        /** DeleteResumeResponse */
        DeleteResumeResponse: {
            /** Id */
            id: string;
            /** Deleted */
            deleted: boolean;
        };
        /** Education */
        Education: {
            /**
             * Institution
             * @default
             */
            institution: string;
            /**
             * Degree
             * @default
             */
            degree: string;
            /** Location */
            location?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Score */
            score?: string | null;
            /** Coursework */
            coursework?: string[];
        };
        /** Experience */
        Experience: {
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Company
             * @default
             */
            company: string;
            /** Location */
            location?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Bullets */
            bullets?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Header */
        Header: {
            /** Full Name */
            full_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Phone */
            phone?: string | null;
            /** Location */
            location?: string | null;
            /** Linkedin */
            linkedin?: string | null;
            /** Github */
            github?: string | null;
            /** Portfolio */
            portfolio?: string | null;
        };
        /** ImprovementChecklistItem */
        ImprovementChecklistItem: {
            /** Text */
            text: string;
            /** Priority */
            priority: string;
            /**
             * Completed
             * @default false
             */
            completed: boolean;
        };
        /** JobDescriptionKeywordMatch */
        JobDescriptionKeywordMatch: {
            /** Keyword */
            keyword: string;
            /** Present */
            present: boolean;
            /** Resume Locations */
            resume_locations?: string[];
            /** Matched Text */
            matched_text?: string[];
        };
        /** KeywordEvidence */
        KeywordEvidence: {
            /** Keyword */
            keyword: string;
            /** Found */
            found: boolean;
            /** Locations */
            locations?: string[];
            /** Matched Text */
            matched_text?: string[];
            /**
             * Confidence
             * @default low
             */
            confidence: string;
        };
        /** KeywordMatch */
        KeywordMatch: {
            /** Keyword */
            keyword: string;
            /** Present */
            present: boolean;
            /** Sources */
            sources?: string[];
        };
        /** MissingKeywordSuggestion */
        MissingKeywordSuggestion: {
            /** Keyword */
            keyword: string;
            /** Safe To Add */
            safe_to_add: boolean;
            /** Suggested Locations */
            suggested_locations?: string[];
            /** Requires Real Knowledge */
            requires_real_knowledge: boolean;
            /** Reason */
            reason: string;
        };
        /** Project */
        Project: {
            /**
             * Name
             * @default
             */
            name: string;
            /** Role */
            role?: string | null;
            /** Link */
            link?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Technologies */
            technologies?: string[];
            /** Bullets */
            bullets?: string[];
        };
        /** RenderTexResponse */
        RenderTexResponse: {
            /** Latex */
            latex: string;
            /** Filename */
            filename: string;
        };
        /** Resume */
        Resume: {
            header: components["schemas"]["Header"];
            /** Professional Summary */
            professional_summary?: string | null;
            /** Skills */
            skills?: components["schemas"]["Skill"][];
            /** Experience */
            experience?: components["schemas"]["Experience"][];
            /** Projects */
            projects?: components["schemas"]["Project"][];
            /** Education */
            education?: components["schemas"]["Education"][];
            /** Certifications */
            certifications?: components["schemas"]["Certification"][];
            /** Achievements */
            achievements?: components["schemas"]["Achievement"][];
            /** Section Order */
            section_order?: components["schemas"]["SectionName"][];
        };
        /** ResumeRecordResponse */
        ResumeRecordResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            resume: components["schemas"]["Resume"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ResumeSaveRequest */
        ResumeSaveRequest: {
            /**
             * Title
             * @default Untitled Resume
             */
            title: string;
            resume: components["schemas"]["Resume"];
        };
        /** RewriteBulletsRequest */
        RewriteBulletsRequest: {
            resume: components["schemas"]["Resume"];
            /**
             * Target Role
             * @default
             */
            target_role: string;
            /**
             * Target Company
             * @default
             */
            target_company: string;
            /**
             * Enable Ai
             * @default false
             */
            enable_ai: boolean;
        };
        /** RewriteBulletsResponse */
        RewriteBulletsResponse: {
            /** Rewrites */
            rewrites?: components["schemas"]["BulletRewrite"][];
            /** Provider */
            provider: string;
            /** Ai Enabled */
            ai_enabled: boolean;
            /** Safety Rules */
            safety_rules?: string[];
        };
        /**
         * SectionName
         * @enum {string}
         */
        SectionName: "professional_summary" | "skills" | "experience" | "projects" | "education" | "certifications" | "achievements";
        /** SectionQualityIssue */
        SectionQualityIssue: {
            /** Section */
            section: string;
            /** Severity */
            severity: string;
            /** Message */
            message: string;
        };
        /** SectionScoreBreakdown */
        SectionScoreBreakdown: {
            /** Section */
            section: string;
            /** Score */
            score: number;
            /** Reason */
            reason: string;
        };
        /** Skill */
        Skill: {
            /**
             * Category
             * @default
             */
            category: string;
            /** Items */
            items?: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    generate_resume_api_resume_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Resume"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_resume_tex_api_resume_render_tex_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Resume"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderTexResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_resume_api_resume_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeResumeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_job_description_api_resume_analyze_job_description_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeJobDescriptionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeJobDescriptionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rewrite_resume_bullets_api_resume_rewrite_bullets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RewriteBulletsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RewriteBulletsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_resume_api_resume_save_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeSaveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeRecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resume_api_resume__resume_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeRecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_resume_api_resume__resume_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeSaveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeRecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_resume_api_resume__resume_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
